name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pnpm:
          - 10.2.0

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pnpm install

    # Linting
    - name: Run linst
      run: pnpm lint

    # Testing
    - name: Run tests
      run: pnpm test

    # Building
    - name: Build the project
      run: pnpm build